### PR TITLE
add I

### PR DESCRIPTION
**Pull request by komal7141**
added #21

### CODE REVIEW

**Comment by codewithnick** [comment]
@komal7141  you have merge conflicts please resolve and update your repo

**Comment by komal7141** [comment]
Screenshot (28)

**Comment by komal7141** [comment]
> @komal7141 you have merge conflicts please resolve and update your repo

resolved it.

**Comment by AnshumanMahato** [comment]
Woah... just removed everything to resolve conflicts 🫡🤯. @komal7141, this is not the way to resolve conflicts. You need to accommodate your changes in a way that it associates with the changes causing the conflict. Don't worry, no big deal (although it could have been one 😅)

Look do this,
1. copy your function code somewhere else
2. reset back to the commit before you added any changes.
3. pull the new changes.
4. add your function.
5. commit and push.

If you get stuck somewhere, ask for help in the community or you may dm me as well.

**Comment by komal7141** [comment]
> Woah... just removed everything to resolve conflicts 🫡🤯. @komal7141, this is not the way to resolve conflicts. You need to accommodate your changes in a way that it associates with the changes causing the conflict. Don't worry, no big deal (although it could have been one 😅)
> 
> Look do this,
> 
> 1. copy your function code somewhere else
> 2. reset back to the commit before you added any changes.
> 3. pull the new changes.
> 4. add your function.
> 5. commit and push.
> 
> If you get stuck somewhere, ask for help in the community or you may dm me as well.

okay sir. thanks for info.
 I will try to do. if I face some problem then i will reach you.

**Pull request closed without merging**
