### PR TITLE
Pull/MergeReqstraight.h

### PR DESCRIPTION
**Pull request by DanielZhang111**
Does this work? If not, could you kind of (give some hints) on what I did wrong, as I am new to Github and am kinda lost on this? Thanks! :)

*Describes your contribution*

### Referenced Issues

closes #issue_number

### CODE REVIEW

**Comment by AnshumanMahato** [comment]
@DanielZhang111 Our project has different fonts that print characters in a specific style style. You can find these fonts in the `Fonts` directory. Each font has two files - a header file and a markdown file. A preview for each character is present in the associated markdown file. You refer to that when defining the function for the character you want to add.

You define the function in the associated Header file. For Straight font, that would be the `straight.h` file. We have already provided the body for all functions in the comments. You need to uncomment and make the required changes. 

Now, each character is a 2D grid. The rows and columns for the grid depend upon the specific character. All you need to do is fill this grid as per the preview.

https://github.com/codewithnick/ascii-art/blob/8afb0692287f19a2af59fd5e6821dec48e54e6f6/Fonts/Straight/straight.h#L188-L197

For testing, you use the `example.cpp` file. Set the font to the font you're working on and print the character.

https://github.com/codewithnick/ascii-art/blob/8afb0692287f19a2af59fd5e6821dec48e54e6f6/example.cpp#L8-L10

I hope this helps answer your question. If there is anything else, feel free to ask.

**Comment by AnshumanMahato** [comment]
As I can see you haven't uncommented the function but have added some lines. You know C++, right?

**Comment by DanielZhang111** [comment]
I'm still kind of confused...

**Comment by AnshumanMahato** [comment]
@DanielZhang111 what programming language do you know?

**Comment by DanielZhang111** [comment]
None :/ I'm new to this lol

**Comment by AnshumanMahato** [comment]
Oh, I see. it's a tricky situation. Well in that case I would suggest you better learn first. Once you become a bit more proficient, feel free to contribute here. I might not be hacktoberfest, but open source stays open all year. I hope you understand @DanielZhang111

**Comment by DanielZhang111** [comment]
Ok, I will come back to this hopefully sometime in the future!

**Comment by AnshumanMahato** [comment]
@DanielZhang111 will look forward to that 🫡

**Comment by DanielZhang111** [comment]
Ok ! :)

**Pull request closed without merging**
