### PR TITLE
Fixed memory leaks and expanded the number of charcaters to print

### PR DESCRIPTION
**Pull request by JakeKilled4**
There was memory leaks because memory was not released properly. I changed the two dimensional arrays  with vectors of strings, and the raw pointers with unique_ptr to avoid to release the memory manually. Before the maximum number of characters in a row was 100, after that the program crushed, I adapted to obtain more space when needed.

### CODE REVIEW

**Comment by codewithnick** [comment]
Thanks for the pr @AnshumanMahato can you please test before merging

**Comment by AnshumanMahato** [comment]
Thanks for Contributing @JakeKilled4 😊🙏. Will check this out on weekend.

**Comment by JakeKilled4** [comment]
This is the result of an example using the font boomer:
image

I attach also some images that shows the memory leaks before and after the commits. This images are the result of the valgrind tool:

Before commits:
prueba


After commits:
image

**Review by AnshumanMahato — APPROVED** [review]
Looks Great. Thanks for contributing @JakeKilled4  🎉🎉✌️

**Pull request merged**
