### PR TITLE
added small o

### LINKED ISSUE #99: Add character: o to font: boomer
*Character* : o
*Font* : boomer

### PR DESCRIPTION
**Pull request by FreemRL**
*Describes your contribution*
added a small o to boomer font.
image
image

### Referenced Issues
#99 

closes #99

### CODE REVIEW

**Comment by AnshumanMahato** [comment]
The centre of O is a bit different in the preview. Please adjust that. You'll find it's preview in the associated md file

**Comment by FreemRL** [comment]
Oh sorry I didn't saw that. I'll adjust it now ^^

**Comment by FreemRL** [comment]
Alright @AnshumanMahato I updated it.

Here's the look now:
image
image

**Comment by AnshumanMahato** [comment]
Everything works fine @FreemRL. Thanks for contributing 😊

**Pull request merged**
