### PR TITLE
508

### LINKED ISSUE #508: Add character: <k> to font: <banner>
*Character* : <k>
*Font* : <banner>
assign me

### PR DESCRIPTION
**Pull request by sandeep131431**
*Describes your contribution*

### Referenced Issues

closes #508

### CODE REVIEW

**Comment by sandeep131431** [comment]
#508

**Review by AnshumanMahato — CHANGES_REQUESTED** [review]
Adjust the grid so that aligns with the rest of the characters. Currently this is happening

image

**Comment by sandeep131431** [comment]
sir ye small latter m banana tha

**Comment by AnshumanMahato** [comment]
@sandeep131431 I understand that. But as you can see, k upar utha hua hai... sabka bottom ek line me hona chahiye

**Comment by sandeep131431** [comment]
Okk sir

**Pull request closed without merging**
