### PR TITLE
code for letter H *RESOLVED

### PR DESCRIPTION
**Pull request by gulshankapse**
Screenshot (3)

### CODE REVIEW

**Comment by sachinkumar911** [comment]
it is boomer font right?

**Comment by gulshankapse** [comment]
yes

**Comment by sachinkumar911** [comment]
okay then you should add it in boomer font. you should not create a new font "ha".resolve it.

**Comment by gulshankapse** [comment]
Screenshot (4)

**Comment by gulshankapse** [comment]
I added my code for letter H in Boomer font

**Comment by AnshumanMahato** [comment]
It's working fine. Thanks for your contribution 🙏

**Pull request merged**
