### PR TITLE
Added character: <4> to font: <drpepper> #731

### PR DESCRIPTION
**Pull request by verma-divyanshu-git**

### CODE REVIEW

**Review by AnshumanMahato — CHANGES_REQUESTED** [review]
image

See drpepper.md file for the design for 4. currently it is printing something else.

**Comment by verma-divyanshu-git** [comment]
Hey @AnshumanMahato , fixed it, can you please check now

**Review by AnshumanMahato — APPROVED** [review]

**Comment by verma-divyanshu-git** [comment]
@AnshumanMahato will I be able to see it on my hacktoberfest contributions? I can't see it yet

**Comment by AnshumanMahato** [comment]
Yes... it should be visible there

**Pull request merged**
